### PR TITLE
allow for enable/disable of specific recover states at runtime

### PR DESCRIPTION
**Pull request by bfalacerda**
also a couple of bug fixes and code clean

### CODE REVIEW

**Comment by Jailander** [comment]
Please tell me it says Stupid humans when _"only complain about lack of proper help when help was offered"_

**Comment by bfalacerda** [comment]
nop, british politeness ;)

**Comment by Jailander** [comment]
:+1: maybe the German version ;)
BTW I will start working on integrate this with policy execution and topological navigation

**Comment by nilsbore** [comment]
I did a brief test of this and the walking group recovery is still working. Will merge a small change after this.

**Comment by marc-hanheide** [comment]
I have one question about the magnetic strip recovery here: How will it be dealt with (read the code but am still not quite sure)? I think when the magnetic strip stop engages it should be "fatal" in a sense that you cannot recover from it by simply asking a human to be pushed. It's our last resort emergency stop and if it happens we need to be notified and the robot needs to be blocked (e.g. not actively go anywhere) until an engineer (AKA us) has checked that it's safe. Otherwise, a human might push the robot passed the magnetic strip and it then goes happily down the stairs again...

**Comment by Jailander** [comment]
When the magnetic sensor is activated you have to call a service called `/reset_barrier_stop` right now that service is only called from the terminal and by pressing start on the gamepad

**Comment by bfalacerda** [comment]
exactly, the "recover" is pretty much putting something on the screen asking to call the robot handler, and tweeting something, if the tweet server is available

**Comment by marc-hanheide** [comment]
brilliant... sorry, just wanted to make sure.

**Pull request merged**
