### PR TITLE
 [backtrack_behaviour] Move speaking into the action server

### PR DESCRIPTION
**Pull request by nilsbore**
Moved speaking from monitored nav states to backtrack, with check if it got a global plan. Only problem is that it might come a bit late right now, the robot starts moving at the same time as speaking. This might be a safety issue. @bfalacerda Do you know of any way to pause movement in move_base to let her finish speaking before moving?

Hold off on merging until we've discussed this.

### CODE REVIEW

**Comment by bfalacerda** [comment]
either 
1. use the wait_for_result() method - I've not being using it because it's blocking and mary sometimes got stuck, but I think that doesn't happen anymore, @cdondrup ?
2. Just hack a sleep() after sending the goal if 1. cannot be used

**Comment by nilsbore** [comment]
@bfalacerda None of these will block move_base, right?

**Comment by bfalacerda** [comment]
No, if your call to move_base isnt sequentially after the mary call these won't work. Directly on move_base I think we'll have to cheat and make min_trans_vel=0 or something like that. I'm not aware of anyway to tell it to pause

**Comment by nilsbore** [comment]
I think it has to be since we want to know if it has gotten a plan when we speak. I'll do some googling.

**Comment by nilsbore** [comment]
@bfalacerda Changed to the proposed solution now. This works on Rosie and can be extended if we want to have different messages for driving forward or backwards etc. I think this is fine to merge for now.

**Comment by bfalacerda** [comment]
tested on bob

**Pull request merged**
