### PR TITLE
[backtrack_behaviour] Move republish_pointcloud_service and previous_positions_service to this package

### PR DESCRIPTION
**Pull request by nilsbore**
This pull
- moves `republish_pointcloud_service` and `previous_positions_service` to `backtrack_behaviour`
- add proper install targets

### CODE REVIEW

**Comment by nilsbore** [comment]
@BFALacerda  There seems to be a problem with the main branch of `strands_recovery_behaviours`, jenkins is complaining about not finding `ros-hydro-strands-navigation-msgs`.

**Comment by bfalacerda** [comment]
yes, from what I understand this will only work when strands_navigation is  properly released. We're in the process of doing it now, so this should be solved soon

**Comment by marc-hanheide** [comment]
it is now released so test this please

**Comment by marc-hanheide** [comment]
BTW "test this please" is a magic phrase to trigger a rebuild

**Comment by marc-hanheide** [comment]
https://lcas.lincoln.ac.uk/jenkins/job/pr-hydro-strands_recovery_behaviours/5/console shows this:

```
monitored_vcs/backtrack_behaviour/CMakeFiles/previous_positions.dir/src/previous_positions.cpp.o
/var/lib/jenkins/workspace/pr-hydro-strands_recovery_behaviours/monitored_vcs/backtrack_behaviour/src/previous_positions.cpp:4:57: fatal error: previous_positions_service/PreviousPosition.h: No such file or directory
```

**Comment by nilsbore** [comment]
Didn't realize I had another workspace sourced, should be fixed now.

**Pull request merged**
