### PR TITLE
removing clear costmaps recovery

### PR DESCRIPTION
**Pull request by bfalacerda**

### CODE REVIEW

**Comment by bfalacerda** [comment]
this will make the backtrack start faster again @cdondrup I will add some speech before starting tomorrow if that's ok

**Comment by bfalacerda** [comment]
solves https://github.com/strands-project/strands_navigation/issues/152

**Comment by lucasb-eyer** [comment]
No, wait.

**Comment by bfalacerda** [comment]
the plot thickens!

**Comment by cdondrup** [comment]
Not a big fan of making it faster... Will be hell in public spaces aka a museum...

**Comment by bfalacerda** [comment]
i'll close this for now as it looks like costmap clearing wasn't the culprit after all

**Pull request closed without merging**
