### PR TITLE
Using parameters to set audio priorities and volumes in walking group recovery

### PR DESCRIPTION
**Pull request by cdondrup**
Not really sure if that works properly. Would love to use parameters to set the volume and priority but this is not really easy for recovery behaviours.

@nilsbore can you please have a look? I'll try that more exhaustively on the robot over or after Easter.

### CODE REVIEW

**Comment by nilsbore** [comment]
Yes, I think this should work, I'll have a look probably tomorrow.

**Comment by marc-hanheide** [comment]
which tomorrow @nilsbore :smirk: ?

**Comment by hawesie** [comment]
:microphone: It's only a day aaaway.

**Comment by hawesie** [comment]
:microphone:

**Comment by marc-hanheide** [comment]
@hawesie clearly is enjoying the dolce vita

**Comment by hawesie** [comment]
TOO MANY SMALL STRONG COFFEES :coffee:

**Comment by bfalacerda** [comment]
the proper stuff!

**Comment by hawesie** [comment]
At €0.80 for a really good coffee here I will definitely feel your pain when I get back.

**Comment by nilsbore** [comment]
@marc-hanheide Working day tomorrow, so today:P.

**Comment by nilsbore** [comment]
@cdondrup I can confirm that setting the parameters this way worked exactly as intended, OK to merge.

**Comment by marc-hanheide** [comment]
thanks!

**Pull request merged**
